language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install . --use-mirrors
  - pip install -r tests/requirements.txt --use-mirrors
script:
  - flake8 iptools
  - flake8 tests
  - nosetests
notifications:
  email:
      - travis-ci+python-iptools@bd808.com
